Repository bcgov/jag-pcss-criminal, pull requests merged in 2021-11, with the labels that each got.

#21 Sync Controller Implementation
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/Keys.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/SyncController.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/synccontroller/GetSyncCriminalAppearanceTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/synccontroller/GetSyncCriminalHearingRestrictionTest.java
Labels: EXTREME DEVOPS, porkchopsandwiches, label, :racing_car:, Questionable, :+1: :-1:, It's Working

#22 Add Dependabot
  .github/dependabot.yml
Labels: :+1: :-1:

#24 Setup Root Elements for secure
  pcss-criminal-secure-model/src/main/resources/xsdSchemas/pcss-secure-2.xsd
Labels: :racing_car:, :+1: :-1:

#23 Implement Personnel Controller
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/Keys.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/PersonnelController.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/personnelcontroller/GetPersonnelAvailDetailTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/personnelcontroller/GetPersonnelAvailabilityTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/personnelcontroller/GetPersonnelSearchTest.java
Labels: EXTREME DEVOPS, porkchopsandwiches, DO NOT MERGE, :racing_car:, Questionable, :+1: :-1:, It's Working

#30 Docker
  .env-template
  Dockerfile
  docker-compose.yml
Labels: EXTREME DEVOPS, :racing_car:, :+1: :-1:

#31 Updating log pattern
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/Keys.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/AppearanceController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/FileController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/PersonnelController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/SyncController.java
Labels: EXTREME DEVOPS, porkchopsandwiches, label, :racing_car:, :+1: :-1:, It's Working

#35 Added hearing controller
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/Keys.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/HearingController.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/hearingcontroller/SetHearingRestrictionCriminalTest.java
Labels: enhancement, label, ICEMAN

#38 Fix personnel controller
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/Keys.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/PersonnelController.java
Labels: EXTREME DEVOPS, porkchopsandwiches, label, :racing_car:, :+1: :-1:, It's Working

#39 Added setCounselDetailCriminal method and tests
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/Keys.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/CrownController.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/crowncontroller/SetCounselDetailCriminalTest.java
Labels: ICEMAN

#43 Implementation and Tests
  pcss-criminal-application/pom.xml
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/Keys.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/SyncController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/SyncValidator.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/SyncValidatorImpl.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/utils/ValidationUtils.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/synccontroller/GetSyncCriminalAppearanceTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/synccontroller/GetSyncCriminalHearingRestrictionTest.java
  pcss-criminal-application/src/test/java/service/syncvalidatorimpl/validateGetSyncCriminalAppearanceTest.java
  pcss-criminal-application/src/test/java/service/syncvalidatorimpl/validateGetSyncCriminalHearingRestrictionTest.java
Labels: EXTREME DEVOPS, porkchopsandwiches, label, :racing_car:, Questionable, :+1: :-1:, It's Working

#47 Check null and blank
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/utils/ValidationUtils.java
Labels: EXTREME DEVOPS, porkchopsandwiches, :racing_car:, Questionable, :+1: :-1:, It's Working

#48 ORDS Implementation
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/Keys.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/AppearanceController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/FileController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/HearingController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/PersonnelController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/SyncController.java
Labels: EXTREME DEVOPS, porkchopsandwiches, label, :racing_car:, :+1: :-1:, It's Working

#53 Temp fixes
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/configuration/SoapConfig.java
  pcss-criminal-common/src/main/java/ca/bc/gov/open/pcsscriminalcommon/serializer/InstantDeserializer.java
  pcss-criminal-common/src/test/java/ca/bc/gov/open/pcsscriminalcommon/serializer/InstantDeserializerTest.java
Labels: porkchopsandwiches

#49 Appearance Validation
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/AppearanceController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/AppearanceValidator.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/HearingValidator.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/AppearanceValidatorImpl.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/HearingValidatorImpl.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/utils/ValidationUtils.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/GetAppearanceCriminalApprMethodSecureTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/GetAppearanceCriminalApprMethodTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/GetAppearanceCriminalCountSecureTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/GetAppearanceCriminalCountTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/GetAppearanceCriminalResourceTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/GetAppearanceCriminalSecureTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/GetAppearanceCriminalTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/SetAppearanceCriminalTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/appearancecontroller/SetAppearanceMethodCriminalTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateGetAppearanceCriminalApprMethodSecureTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateGetAppearanceCriminalApprMethodTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateGetAppearanceCriminalCountSecureTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateGetAppearanceCriminalCountTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateGetAppearanceCriminalResourceTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateGetAppearanceCriminalSecureTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateGetAppearanceCriminalTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateSetAppearanceCriminalTest.java
  pcss-criminal-application/src/test/java/service/appearancevalidatorimpl/ValidateSetAppearanceMethodCriminalTest.java
  pcss-criminal-application/src/test/java/service/hearingvalidatorimpl/ValidateSetHearingRestrictionCriminalTest.java
Labels: EXTREME DEVOPS, porkchopsandwiches, label, :racing_car:, Questionable, :+1: :-1:, It's Working, LARGE

#54 getCrownAssignment endpoint validations
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/CrownController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/HearingController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/CrownValidator.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/AppearanceValidatorImpl.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/CrownValidatorImpl.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/HearingValidatorImpl.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/SyncValidatorImpl.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/utils/ValidationUtils.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/crowncontroller/GetCrownAssignmentTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/crowncontroller/SetCounselDetailCriminalTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/crowncontroller/SetCrownAssignmentTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/crowncontroller/SetCrownFileDetailTest.java
  pcss-criminal-application/src/test/java/service/crownvalidatorimpl/ValidateGetCrownAssignmentTest.java
  pcss-criminal-application/src/test/java/service/hearingvalidatorimpl/ValidateSetHearingRestrictionCriminalTest.java
Labels: enhancement

#58 Crown Validation
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/CrownController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/HearingController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/CrownValidator.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/CrownValidatorImpl.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/HearingValidatorImpl.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/crowncontroller/SetCounselDetailCriminalTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/crowncontroller/SetCrownAssignmentTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/crowncontroller/SetCrownFileDetailTest.java
  pcss-criminal-application/src/test/java/service/crownvalidatorimpl/ValidateSetCounselDetailCriminalTest.java
  pcss-criminal-application/src/test/java/service/crownvalidatorimpl/ValidateSetCrownAssignmentTest.java
  pcss-criminal-application/src/test/java/service/crownvalidatorimpl/ValidateSetCrownFileDetailTest.java
Labels: porkchopsandwiches, :racing_car:, :+1: :-1:

#59 Personnel Controller Validation
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/PersonnelController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/PersonnelValidator.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/PersonnelValidatorImpl.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/personnelcontroller/GetPersonnelAvailDetailTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/personnelcontroller/GetPersonnelAvailabilityTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/personnelcontroller/GetPersonnelSearchTest.java
  pcss-criminal-application/src/test/java/service/personnelvalidatorimpl/ValidateGetPersonnelAvailDetailTest.java
  pcss-criminal-application/src/test/java/service/personnelvalidatorimpl/ValidateGetPersonnelAvailabilityTest.java
  pcss-criminal-application/src/test/java/service/personnelvalidatorimpl/ValidateGetPersonnelSearchTest.java
Labels: porkchopsandwiches, :racing_car:, :+1: :-1:

#60 File Controller Validation
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/controller/FileController.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/FileValidator.java
  pcss-criminal-application/src/main/java/ca/bc/gov/open/pcsscriminalapplication/service/impl/FileValidatorImpl.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/filecontroller/GetClosedFileTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/filecontroller/GetFileDetailCriminalSecureTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/filecontroller/GetFileDetailCriminalTest.java
  pcss-criminal-application/src/test/java/ca/bc/gov/open/pcsscriminalapplication/controller/filecontroller/SetFileNoteTest.java
  pcss-criminal-application/src/test/java/service/filevalidationimpl/ValidateGetClosedFileTest.java
  pcss-criminal-application/src/test/java/service/filevalidationimpl/ValidateGetFileDetailCriminalSecureTest.java
  pcss-criminal-application/src/test/java/service/filevalidationimpl/ValidateGetFileDetailCriminalTest.java
  pcss-criminal-application/src/test/java/service/filevalidationimpl/ValidateSetFileNoteTest.java
Labels: porkchopsandwiches, label, :racing_car:, :+1: :-1:, It's Working
